### ISSUE TITLE
seahorse-nautilus?

### ISSUE THREAD

**Issue by felipehw** [flathub/org.gnome.seahorse.Application#5]
Hi. Is there a way to integrate this Flatpak with Nautilus?

Maybe a plugin of `seahorse-nautilus` to this Flatpak? I don't know if this is possible or makes sense ...

**Comment by mpi3d** [comment]
According to the content of the package in fedora: https://packages.fedoraproject.org/pkgs/seahorse-nautilus/seahorse-nautilus/fedora-38.html

We can provide this:
+ `seahorse-pgp-encrypted.desktop`
+ `seahorse-pgp-keys.desktop`
+ `seahorse-pgp-signature.desktop`

But we will be unabe to write `libnautilus-seahorse.so` inside nautilus extensions.

This means that "Encrypt" and "Sign" option will **not** be shown:

![Encrypt Sign](https://github.com/flathub/org.gnome.seahorse.Application/assets/26822551/b382f02e-7527-40a0-b1ec-e64bcdcd18f9)

But "Decrypt File", "Import Key" and "Verify Signature" will be shown and will be usable :

![Decrypt](https://github.com/flathub/org.gnome.seahorse.Application/assets/26822551/b05410cd-f735-4bcc-9c9e-eca439265a50)
![Import](https://github.com/flathub/org.gnome.seahorse.Application/assets/26822551/6409610f-7d39-4fde-acc7-268231402124)
![Verify](https://github.com/flathub/org.gnome.seahorse.Application/assets/26822551/55daa7ac-f6ee-4ec6-9e18-20dc76b92526)

But anyway, I don't think it's good to provide a half working extension. So I would say that it's not possible to use `seahorse-nautilus` as a Flatpak.

**Comment by nielsdg** [comment]
Seahorse-nautilus is badly-named, as it has noting to do with seahorse, except for some historical ties. It had several issues as well, and was completely unmaintained, so it's been archived upstream.
